### ISSUE TITLE
Add easy_infra

### ISSUE THREAD

**Issue by virtualroot** [virtualroot/awesome-opentofu#10]
Add wrapper once https://github.com/SeisoLLC/easy_infra/pull/299 is merged.

**Comment by JonZeolla** [comment]
@virtualroot this will be merging this week 🙏

**Comment by JonZeolla** [comment]
This shipped yesterday https://hub.docker.com/r/seiso/easy_infra/tags?page=1&name=opentofu

**Comment by virtualroot** [comment]
Thanks @JonZeolla
