### ISSUE TITLE
Slack link doesn't work

### ISSUE THREAD

**Issue by MathiasLorenz** [virtualroot/awesome-opentofu#4]
When I press the link for the Slack Workspace I get the below error. I don't know if you can make a more 'permanent' Slack invite link though.

![image](https://github.com/virtualroot/awesome-opentofu/assets/29771208/c911f336-2670-4ae6-9442-0f146544f4ce)

**Comment by virtualroot** [comment]
Good catch!

I took the link from their README.md. It seems they are using https://opentofu.org/slack for the redirect.
