### ISSUE TITLE
List of places where TF has been superseded by OpenTofu?

### ISSUE THREAD

**Issue by RDhar** [virtualroot/awesome-opentofu#63]
Do we happen to have a list of places where TF has been superseded by OpenTofu? For example:

* [GitLab opted to migrate](https://gitlab.com/components/opentofu#migrating-from-the-terraform-cicd-templates) its TF CI/CD pipeline templates to OpenTofu.
* [Brew stopped updating](https://formulae.brew.sh/formula/terraform) TF beyond MPL-2.0 licensed v1.5.7.
* [Alpine Linux](https://gitlab.alpinelinux.org/alpine/aports/-/issues/15193) dropped support for TF going forward.

I'm sure there must be others?

**Comment by kvendingoldo** [comment]
At this moment if you need to have a support of Terraform as well as OpenTofu (and Terragrunt :) ) in one tool you can use https://github.com/tofuutils/tenv which my team wrote some months ago. A lot of users switched to that tool to unify version management in the world of Terraform. 

You're welcome to open any issues or contribute to [tenv](https://github.com/tofuutils/tenv).

**Comment by RDhar** [comment]
Thanks, @kvendingoldo! 

For the [DevSecTop/TF-via-PR](https://github.com/DevSecTop/TF-via-PR) project (which enables CI-driven automated provisioning of (O)TF via Pull Request interaction workflow), I've gone ahead and added a [functional demo workflow](https://github.com/DevSecTop/TF-via-PR-Comments/blob/tenv-examples/.github/workflows/tf_tests.yml#L34-L36) relying on `tenv`.

Not only that, but `tenv` is at the heart of running tests in matrix-strategy, comparing `tofu` and `terraform` outputs simultaneously, side-by-side on the same PR.

Massively appreciative of @dvaumoron and yourself for responding to my requests (https://github.com/tofuutils/tenv/issues/92, https://github.com/tofuutils/tenv/issues/93, https://github.com/tofuutils/tenv/issues/98) and supporting supporting `GITHUB_OUTPUT` feature parity with the likes of [setup-opentofu](https://github.com/opentofu/setup-opentofu) and [setup-terraform](https://github.com/hashicorp/setup-terraform) GH Actions.

**Comment by virtualroot** [comment]
Please consider looking at https://github.com/northwood-labs/opentofu-support and opening an issue there; it seems to be a better place for this than this issue.
